Energetic Chocolate Weasel

Medium

# `CrossChainRouter::_handleLiquidationFailure` improperly handles cross-chain liquidation failure

### Summary

`CrossChainRouter::_handleLiquidationFailure` improperly handles cross-chain liquidation failure (details below).

### Details
Consider the case where a user cross-chain borrows `ChainB_USDC` tokens on chainB backed by the `ChainA_WETH` collateral on chainA. Liquidator calls `CrossChainRouter::liquidateCrossChain` to liquidate user's cross-chain borrow position. The liquidator's call follows the simplified call trace below and ends at `CrossChainRouter::_handleLiquidationFailure`.

1. ChainB: Liquidator calls `CrossChainRouter::liquidateCrossChain`
2. ChainB: `CrossChainRouter::_executeLiquidation`
3. ChainB: `CrossChainRouter::_executeLiquidationCore`
4. ChainB: `CrossChainRouter::_send`
5. ChainA: `CrossChainRouter::_lzReceive`
6. ChainA: `CrossChainRouter::_checkLiquidationValid` (false for liquidation failure)
7. ChainA: `CrossChainRouter::_sendLiquidationFailure`
8. ChainA: `CrossChainRouter::_send`

```javascript
        _send(
            _dstEid: ChainB_Eid,
            _amount: payload.amount,
            _borrowIndex: 0,
            _collateral: 0,
            _sender: payload.sender,            // user address
            _destlToken: payload.destlToken,    // ChainA_lWETH
            _liquidator: payload.liquidator,
            _srcToken: payload.srcToken,        // ChainB_USDC
            ctype: ContractType.LiquidationFailure
        );
```

9.  ChainB: `CrossChainRouter::_lzReceive`
10. ChainB: `CrossChainRouter::_handleLiquidationFailure`

Throughout this call trace, tokens were not taken (`transferFrom`) liquidator. It is only taken from liquidator in the "`_checkLiquidationValid` returns `true`" code path. However, `CrossChainRouter::_handleLiquidationFailure` attempts to refund the liquidator. Fortunately, a mistake in `CrossChainRouter::_handleLiquidationFailure` prevents the transferring of funds. Nonetheless, the function call will still revert unexpectedly, causing an improper handling of cross-chain liquidation failure.

[`CrossChainRouter::_handleLiquidationFailure#L478-L485`](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/713372a1ccd8090ead836ca6b1acf92e97de4679/Lend-V2/src/LayerZero/CrossChainRouter.sol#L478-L485)
```javascript
     * @dev - Received on Chain A. // <@ no, received on chainB
    function _handleLiquidationFailure(LZPayload memory payload) private {
        address underlying = lendStorage.lTokenToUnderlying(payload.destlToken);
        //                 = lendStorage.lTokenToUnderlying(ChainA_lWETH);
        //                 = ChainA_WETH (if "ChainA_lWETH to ChainA_WETH" mapping even exist on chainB)

        // Refund the liquidator
        IERC20(underlying).safeTransfer(payload.liquidator, payload.amount);
        // IERC20(ChainA_WETH).safeTransfer(payload.liquidator, payload.amount);
        // ChainA_WETH does not exist on ChainB as tokens usually have different addresses on different chains
        // CrossChainRouter also does not posses the funds amount requested in the safeTransfer
        // safeTransfer fails and reverts

        emit LiquidationFailure(payload.liquidator, payload.destlToken, payload.sender, underlying);
    }
```

### Root Cause

In [`CrossChainRouter::_handleLiquidationFailure#L478-L485`](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/713372a1ccd8090ead836ca6b1acf92e97de4679/Lend-V2/src/LayerZero/CrossChainRouter.sol#L478-L485), the function attempts to refund the liquidator eventhough `CrossChainRouter::liquidateCrossChain` call trace does not take (`transferFrom`) tokens from the liquidator.

[`CrossChainRouter::_handleLiquidationFailure#L478-L485`](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/713372a1ccd8090ead836ca6b1acf92e97de4679/Lend-V2/src/LayerZero/CrossChainRouter.sol#L478-L485)

```javascript
    function _handleLiquidationFailure(LZPayload memory payload) private {
@>      address underlying = lendStorage.lTokenToUnderlying(payload.destlToken);
        // Refund the liquidator
@>      IERC20(underlying).safeTransfer(payload.liquidator, payload.amount);
        emit LiquidationFailure(payload.liquidator, payload.destlToken, payload.sender, underlying);
    }
```

### Internal Pre-conditions

`CrossChainRouter::_checkLiquidationValid` returns false

### External Pre-conditions

None

### Attack Path

(refer details section)

### Impact

Improper handling of cross-chain liquidation failure

### PoC

(refer details section)

### Mitigation

Remove the following lines from [`CrossChainRouter::_handleLiquidationFailure#L478-L485`](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/713372a1ccd8090ead836ca6b1acf92e97de4679/Lend-V2/src/LayerZero/CrossChainRouter.sol#L478-L485)

[`CrossChainRouter::_handleLiquidationFailure#L478-L485`](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/713372a1ccd8090ead836ca6b1acf92e97de4679/Lend-V2/src/LayerZero/CrossChainRouter.sol#L478-L485)

```diff
    function _handleLiquidationFailure(LZPayload memory payload) private {
-       address underlying = lendStorage.lTokenToUnderlying(payload.destlToken);
-       // Refund the liquidator
-       IERC20(underlying).safeTransfer(payload.liquidator, payload.amount);
        emit LiquidationFailure(payload.liquidator, payload.destlToken, payload.sender, underlying);
    }
```